//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBalance.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlightBalance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the aircraft from file. Some data may not have been retrieved when the app started..
        /// </summary>
        internal static string AircraftLoadError {
            get {
                return ResourceManager.GetString("AircraftLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the aircraft to file. Some data may not be retrieved when the app restarts..
        /// </summary>
        internal static string AircraftSaveError {
            get {
                return ResourceManager.GetString("AircraftSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm.
        /// </summary>
        internal static string Arm {
            get {
                return ResourceManager.GetString("Arm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callsign.
        /// </summary>
        internal static string Callsign {
            get {
                return ResourceManager.GetString("Callsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CG position.
        /// </summary>
        internal static string CgPosition {
            get {
                return ResourceManager.GetString("CgPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this object?.
        /// </summary>
        internal static string DeleteWarningMessage {
            get {
                return ResourceManager.GetString("DeleteWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aircraft entry is invalid. Please check that the following conditions are met:
        ///
        ///- All information fields are filled
        ///- At least one station entry exists
        ///- At least one envelope entry exists.
        /// </summary>
        internal static string InvalidAircraftEntryError {
            get {
                return ResourceManager.GetString("InvalidAircraftEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The envelope entry is invalid. Please check that the following conditions are met:
        ///
        ///- All fields are filled with values of the correct type
        ///- At least two chart point entries exist
        ///- All chart point weights are greater than zero.
        /// </summary>
        internal static string InvalidEnvelopeEntryError {
            get {
                return ResourceManager.GetString("InvalidEnvelopeEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The station entry is invalid. Please check that the following conditions are met:
        ///
        ///- All fields are filled with values of the correct type
        ///- Weight is greater than zero.
        /// </summary>
        internal static string InvalidFixedStationEntryError {
            get {
                return ResourceManager.GetString("InvalidFixedStationEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The station entry is invalid. Please check that the following conditions are met:
        ///
        ///- All fields are filled with values of the correct type
        ///- Min weight is positive
        ///- Max weight is greater than min weight.
        /// </summary>
        internal static string InvalidVariableStationEntryError {
            get {
                return ResourceManager.GetString("InvalidVariableStationEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is fuel?.
        /// </summary>
        internal static string IsFuel {
            get {
                return ResourceManager.GetString("IsFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max weight.
        /// </summary>
        internal static string MaxWeight {
            get {
                return ResourceManager.GetString("MaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min weight.
        /// </summary>
        internal static string MinWeight {
            get {
                return ResourceManager.GetString("MinWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of points.
        /// </summary>
        internal static string NumberOfPoints {
            get {
                return ResourceManager.GetString("NumberOfPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weight.
        /// </summary>
        internal static string TotalWeight {
            get {
                return ResourceManager.GetString("TotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
